### ISSUE TITLE
Upgrade to Dremio ver. 20+

### ISSUE THREAD

**Issue by hmelnoff** [viktordremio/dremio-sap-hana-connector#1]
Hello, viktorgitdev. First of all I want to thank you for the great job! But unfortunately I met issues with compiling application for using it with Dremio 20.1.0. Could you please tell me if you have some plans to update the code and to add compatibility with newer versions of Dremio? And if no, could you please tell me if there are some difficulties in such job so I could ask developers in our company to continue develop your application.

Thank you and have a nice day!

**Comment by viktorgitdev** [comment]
@hmelnoff I just changed the code to support 20.1. Can you please build "mvn clean install" and test if you can connect to HANA

**Comment by viktorgitdev** [comment]
tested with dremio 21.2. All works now
